# Generated by Django 5.2.4 on 2025-07-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('voice_file', models.FileField(blank=True, null=True, upload_to='voices/')),
                ('face_image', models.ImageField(blank=True, null=True, upload_to='faces/')),
                ('typing_data', models.TextField(blank=True, null=True)),
                ('result', models.CharField(blank=True, max_length=255, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
